-- MySQL Script generated by MySQL Workbench
-- 09/22/16 13:32:08
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cinema
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cinema` ;

-- -----------------------------------------------------
-- Schema cinema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cinema` DEFAULT CHARACTER SET latin1 ;
USE `cinema` ;

-- -----------------------------------------------------
-- Table `cinema`.`film`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`film` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `year` INT(11) NULL DEFAULT NULL,
  `duration` INT(11) NULL DEFAULT NULL,
  `genre` VARCHAR(70) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `country` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `produser` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `cast` VARCHAR(100) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `description` VARCHAR(500) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `smallposter` VARCHAR(200) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `bigposter` VARCHAR(200) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `cinema`.`hall`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`hall` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL DEFAULT 'Красный зал',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `cinema`.`structure`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`structure` (
  `raw` INT(11) NOT NULL,
  `columns` INT(11) NOT NULL,
  `hallID` INT(11) NOT NULL,
  PRIMARY KEY (`hallID`, `raw`),
  CONSTRAINT `hallID`
    FOREIGN KEY (`hallID`)
    REFERENCES `cinema`.`hall` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `cinema`.`session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`session` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `filmID` INT NOT NULL,
  `datetime` DATETIME NULL,
  `hallID` INT NOT NULL,
  `price` DECIMAL(10,4) NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `session_unique` (`datetime`, `hallID`),
  INDEX `fk_session_film1_idx` (`filmID` ASC),
  INDEX `fk_session_hall_idx` (`hallID` ASC),
  CONSTRAINT `fk_session_film`
    FOREIGN KEY (`filmID`)
    REFERENCES `cinema`.`film` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_session_hall`
    FOREIGN KEY (`hallID`)
    REFERENCES `cinema`.`hall` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `cinema`.`userrole`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`userrole` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `cinema`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL DEFAULT 'User',
  `passwd` VARCHAR(50) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `email` VARCHAR(50) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `name` VARCHAR(50) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `surname` VARCHAR(60) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `birthday` DATE NULL DEFAULT NULL,
  `roleID` INT(11) NOT NULL,
  `sex` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `role_id_idx` (`roleID` ASC),
  CONSTRAINT `role_id`
    FOREIGN KEY (`roleID`)
    REFERENCES `cinema`.`userrole` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `cinema`.`ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`ticket` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `raw` INT NULL,
  `col` INT NULL,
  `chk` TINYINT(1) NULL,
  `purchase` TINYINT(1) NULL,
  `timecreate` TIMESTAMP(1) NULL,
  `sessionID` INT NULL,
  `userID` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ticket_key` (`raw`, `col`, `sessionID`),
  INDEX `user_id_idx` (`userID` ASC),
  INDEX `session_id_idx` (`sessionID` ASC),
  CONSTRAINT `user_id`
    FOREIGN KEY (`userID`)
    REFERENCES `cinema`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `session_id`
    FOREIGN KEY (`sessionID`)
    REFERENCES `cinema`.`session` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
